spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:refactoring;DB_CLOSE_DELAY=-1;MODE=Mariadb
    username: sa
    password:
  sql:
    init:
      mode: always
      username: sa
      password:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console


mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

logging:
  level:
    root: debug
